### ISSUE TITLE
Storage in a different bucket

### ISSUE THREAD

**Issue by cocococosti** [overhangio/openedx-scorm-xblock#13]
Hello, more than an issue this is a question.

I have this setting in my Open Edx installation (Ironwood): EDXAPP_AWS_STORAGE_BUCKET_NAME

I just installed this xblock and is saving everything in the bucket in EDXAPP_AWS_STORAGE_BUCKET_NAME.

I have other sensitive files in EDXAPP_AWS_STORAGE_BUCKET_NAME, so I can't make this bucket public. And the xblock seems to only work when the bucket has public access.

Is there an alternative to this? Am I missing a setting?

Thank you!

**Comment by regisb** [comment]
Hi! As a general rule, please don't use Github issues for questions. Instead, please go to the official forums: https://discuss.overhang.io/ (I guess I should have mentioned that in the readme, sorry about that :slightly_smiling_face:)

I believe this is what you are looking for: https://github.com/overhangio/openedx-scorm-xblock/#custom-storage-backends
