### ISSUE TITLE
very slow uploads when using the S3 backend

### ISSUE THREAD

**Issue by sampaccoud** [overhangio/openedx-scorm-xblock#14]
Our users reported timeouts when uploading Scorm modules. We had to drastically increase timeouts on our web servers to solve the issue but, digging a little bit, we think uploads are abnormally slow.

On first glance, the sequence of events happening while the user is holding the request is:
- upload archive from user to S3 via the app
- download archive from S3 to app
- unzip archive in app
- push unzipped files from app to S3

This seems far too many things to do while holding on a user request. It could be improved:

1. upload the archive to a temp file or memory in the first place so it can be unzipped directly

or 

2. upload the zip file to S3 in the request and subcontract the unzipping to Celery asynchronously

Even more efficient would be to upload directly to S3 with an upload policy... and the unzipping could be done directly in S3 via a lambda trigger but it would not work for alternative S3 hosting, swift, etc. so I think the two first solutions are better for the OpenEdX community.

**Comment by regisb** [comment]
I think your analysis of the problem is correct @sampaccoud. Can you just specify which version of the xblock you are running?

**Comment by sampaccoud** [comment]
We are running `openedx-scorm-xblock==9.2.5` on Hawthorn.
Yes, we also feel that the zip file should be trashed after being unzipped...

**Comment by regisb** [comment]
Solved in v10.1.0 and v9.3.0.
