### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by taufanbudiman** [overhangio/openedx-scorm-xblock#15]
Hi, i use openedx hawtorn and install this scorm, but I get an error 404 like this
`https://studio.tenderhub.co/media/scorm/fe91445bbce14be9a9fd6540583cb398/a12799583718dbe103b6c9181d71d93d0888e488/proxy/scorm/script_00046.emt.html`

i only install it by `pip install openedx-scorm-xblock`

![image](https://user-images.githubusercontent.com/25677261/101852826-1398a680-3b91-11eb-85c6-533267c7cc80.png)

**Comment by regisb** [comment]
Hi! this is not the grading issue you mentioned on [this page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/59375819/SCORM+in+Open+edX+Home?focusedCommentId=2125726014#comment-2125726014), right? For support, please go to the Tutor [community forums](https://discuss.overhang.io).

I have no idea what could the error be, as I don't know your nginx configuration or the Open edX/xblock versions that you are using. I expressly remind you that Hawthorn is _not_ supported.

**Comment by regisb** [comment]
I encourage you to try out this xblock with Tutor and see if it works for you.
