### ISSUE TITLE
Required settings modification in native builds

### ISSUE THREAD

**Issue by lpm0073** [overhangio/openedx-scorm-xblock#18]
in native builds on Lilac (perhaps other versions as well) you have to change the following setting found in both edx/etc/lms.yml and /edx/etc/studio.yml:

change this: 
`X_FRAME_OPTIONS: DENY`

to this:
`X_FRAME_OPTIONS: SAMEORIGIN`

**Comment by regisb** [comment]
Thanks for the heads up Lawrence! I added some instructions to the README.
