### ISSUE TITLE
scorm-xblock not compatible with edx-completion

### ISSUE THREAD

**Issue by Ian2012** [overhangio/openedx-scorm-xblock#19]
Our installation is in Lilac and the xblock is not sending the completion correctly.

After some testing we back from v12.0.0 to v11.1.1. This [commit](https://github.com/overhangio/openedx-scorm-xblock/commit/57064625dce7575e07a6a509151b1e05cbcc7ec6) broke the completion.

We are not sure how to resolve the issue. We can make the changes but we are not sure which was the issue you were trying to solve in the commit.

@regisb

**Comment by regisb** [comment]
Hi,
The current supported version of the openedx-scorm xblock is Nutmeg. Unfortunately we are unable to provide support for older versions. As far as I know, v12.1.0 should support completion events. I encourage you to describe your issue more precisely in the Open edX forum: https://discuss.openedx.org/
