### ISSUE TITLE
Support cmi.core.student_id/cmi.learner_id

### ISSUE THREAD

**Issue by potapuff** [overhangio/openedx-scorm-xblock#20]
Hi to all

Is it possible to backport from raccoongang/edx_xblock commit with support of retrieving  student identity? This part is very important in case with several different scorm object in on course. 

https://github.com/raccoongang/edx_xblock_scorm/commit/977c0e9186d04e28f09f396370372ed56e48e13c

Sorry, I don't have enough knowledge in python and testing of EdX  to submit this as a pull request.

**Comment by potapuff** [comment]
Attach pull-request with changes

**Comment by regisb** [comment]
Closed by #21
