### ISSUE TITLE
Nginx 404 in CMS

### ISSUE THREAD

**Issue by taufanbudiman** [overhangio/openedx-scorm-xblock#33]
Hi everyone,

I tried uploading scorm and got an error file not found in nginx, as below
<img width="1011" alt="image" src="https://github.com/overhangio/openedx-scorm-xblock/assets/25677261/a11ed70f-02fe-4ecb-b7af-6b5109d53393">

when I check the console there is an .html file that is not found
<img width="963" alt="image" src="https://github.com/overhangio/openedx-scorm-xblock/assets/25677261/1ba4014b-20bc-4fe8-bd2c-ef31889807ed">

<img width="1506" alt="image" src="https://github.com/overhangio/openedx-scorm-xblock/assets/25677261/6df3f5fe-2d7f-47fd-823d-abe5c9e75aed">

then I looked for the results of extracting the scorm file, I also couldn't find the .html file
<img width="1029" alt="image" src="https://github.com/overhangio/openedx-scorm-xblock/assets/25677261/03803905-86a7-4352-a965-9aa3a513ff36">

when I try to unzip the file that I uploaded, the result is like this. there are some folders that don't exist on the server.
<img width="777" alt="image" src="https://github.com/overhangio/openedx-scorm-xblock/assets/25677261/20b6e9a1-849f-4931-a301-af3b30d9ef85">

how can i fix this problem?

openedx-scorm-xblock Version: 16.0.0
Openedx lilac.master
installation native (not tutor)

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing

Concerning your specific problem: if you run Lilac, you should not install version 16 of the xblock. You should install v12 ([L = 12](https://docs.tutor.overhang.io/tutor.html#versioning)). Also, previous versions of Open edX are unsupported. And I never tried running the xblock in the native installation -- though there is no reason to believe it should not work.
