### ISSUE TITLE
404 not found index.html

### ISSUE THREAD

**Issue by rackarmattan** [overhangio/openedx-scorm-xblock#4]
I installed the scorm xblock on a juniper instance of open edx two days ago (17/8). When I've uploaded a zip-file with the imsmanifest.xml file at the top of the file structure, I get a 404 not found error. I have double-checked, and the scorm packet is saved in this structure: `/edx/var/edxapp/media/scorm/'long_string'/'another_long_string'/index.html` . The GET request is trying to get `http://mydomain.com:18010/media/scorm/'same_long_string'/'another_same_long_string'/index.html`. I haven't made any changes to where the scorm content is supposed to be saved, nor any changes to the nginx configuration (just installed the xblock and tried it out).

**Comment by regisb** [comment]
Can you share the zip file that causes the issue @rackarmattan?

**Comment by rackarmattan** [comment]
Here is the zip file, I tried with another one too but I get the same problem. 
[AnEvolveTestCourse.zip](https://github.com/overhangio/openedx-scorm-xblock/files/5095212/AnEvolveTestCourse.zip)

**Comment by regisb** [comment]
Unfortunately I can't help you further, as I don't run Open edX with the native installation. All I can say is that it works with Tutor. You should make sure that nginx properly serves media files and has the following directive (or similar):

```
  location ~ ^/media/(?P<file>.*) {
    root /edx/var/edxapp/media;
    try_files /$file =404;
    expires 31536000s;
  }
```

**Comment by deepdad** [comment]
@[rackarmattan](https://github.com/rackarmattan) that AnEvolveTestCourse.zip is mine, are you having problems with it? Or are you PW?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rackarmattan** [comment]
Sorry, I think I found it when i scouted for someone else having the same problems as I. I only use it to test if it works to upload a scorm file in the xblock, is that OK? The problem is that I get a 404 when I have uploaded a course. The courses get uploaded and unzipped on the server, but when they are supposed to show up in the xblock, I get a 404 message inside the block. 

![image](https://user-images.githubusercontent.com/24456064/90628523-0fc9c880-e21e-11ea-8f9e-ff383e01bb1f.png)

**Comment by deepdad** [comment]
Haha. Sorry, but this SCORM doesn't work. see issue 3.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rackarmattan** [comment]
Haha okey thanks! It doesn't work with my other scorm file either, so I don't think that's the issue at least, but good to know.

**Comment by rackarmattan** [comment]
Hi again! I just wanted to tell you that the xblock works on a native installation of juniper if you add (as you mentioned):
```
  location ~ ^/media/(?P<file>.*) {
    root /edx/var/edxapp/media;
    try_files /$file =404;
    expires 31536000s;
  }
```
to `/edx/app/nginx/sites-available/cms` . After I did that thuogh, no content of any courses wanted to appear in the LMS. I don't know if that was really the issue, but after adding:
```
location ~ ^/static/bundles/(?P<file>.*){
   try_files /staticfiles/studio/bundles/$file =404;
}
```
inside the `location ~ ^/static/(?P<file>.*)` block in `/edx/app/nginx/sites-available/lms`, everything seems to work fine again.

**Comment by 0xbs0d** [comment]
I'm having the exact same problem but with apache. Any chance someone can help me with configuration?

**Comment by regisb** [comment]
@0xbs0d please do not use Github issues to ask for help. Instead, go to the official community forums: https://discuss.overhang,io

**Comment by 0xbs0d** [comment]
@regisb I apologize and thank you for directing me to the proper place
