### ISSUE TITLE
assets_proxy / querystring_auth performance

### ISSUE THREAD

**Issue by bryanlandia** [overhangio/openedx-scorm-xblock#40]
It's a nice feature addition, but I'm curious if anyone is using assets_proxy with querystring auth on a production site.  Making a new request to an LMS XBlock handler for every single asset as the contents of a SCORM package render to the browser is exceedingly slow.   Normal Django static URL loading using querystring_auth is reasonable because the URLs should all be calculated on one request to the LMS, during template rendering.  Feel free to close as this is more of a comment.

**Comment by regisb** [comment]
Hi Bryan,
Please help me better understand your comment:

1. Why would `querystring_auth=True` considerably slow down performance?
2. This feature was implemented to make it possible to serve SCORM assets from an S3 bucket with querystring authentication. Unless I'm mistaken, querystring auth is required unless we make the bucket public. Do you have an alternative solution to support that use case?

**Comment by regisb** [comment]
Closing this now. Please re-open if you think we still need to discuss this.
