### ISSUE TITLE
Does this XBlock require a player e.g. the JCA Player?

### ISSUE THREAD

**Issue by OmarIthawi** [overhangio/openedx-scorm-xblock#5]
[Another XBlock](https://github.com/appsembler/edx_xblock_scorm#using-ansible) does. 

I guess this one doesn't need the JCA Player but the README has no mention about it.

**Comment by regisb** [comment]
I have no idea what is the JCA player -- but if it were required, it would definitely be indicated in the docs :wink: Note that this xblock also does not require Flash, a Java Runtime Environment or a working Windows server :trollface:
