### ISSUE TITLE
SCORM xblock missing navigation menu

### ISSUE THREAD

**Issue by rax-ar** [overhangio/openedx-scorm-xblock#53]
Hello,

I recently installed the SCORM xblock "https://github.com/overhangio/openedx-scorm-xblock" on my Open edX tutor Palm.

I tried to export a course from eXeLearning to SCORM 1.2 or 2004 format to upload to my Open edX.

When I upload the scorm package in Open edX I can only see the first page of the course. A negation menu is supposed to appear to move through all the sections of the course, or alternatively some buttons for "next" and "previous" but it doesn't.

![Captura](https://github.com/overhangio/openedx-scorm-xblock/assets/129513852/9035945e-910b-4eb1-9961-75531dda874f)

I guess it is some xblock problem because I have uploaded the same package to another LMS platform and to scorm cloud and I can see the menu and navigation buttons.

![Captura1](https://github.com/overhangio/openedx-scorm-xblock/assets/129513852/16122f8b-6d8f-40b7-8f7a-ef0afa57d139)

Any ideas or suggestions?

Thanks in advance. Best regards.

**Comment by ziafazal** [comment]
Hi @rax-ar 
Can you share SCORM package you are using while experiencing this issue or is there any public SCOMR package which we can use to reproduce this issue?

**Comment by rax-ar** [comment]
> Hi @rax-ar Can you share SCORM package you are using while experiencing this issue or is there any public SCOMR package which we can use to reproduce this issue?

Dear @ziafazal 

Thanks for your reply. Sure, there is no problem in sharing my scorm package with you.

I have exported it in the following formats: 1.2, 2004 and IMS. 
[IMS.zip](https://github.com/overhangio/openedx-scorm-xblock/files/13558093/IMS.zip)
[SCORM1.2.zip](https://github.com/overhangio/openedx-scorm-xblock/files/13558094/SCORM1.2.zip)
[SCORM2004.zip](https://github.com/overhangio/openedx-scorm-xblock/files/13558096/SCORM2004.zip)


Please let me know if you need anything else. 

Best regards,

rax

**Comment by ziafazal** [comment]
@rax-ar at moments Scorm Xblock does not have ability to build either Navigation buttons or course outline from SCORM package metadata. You have to build/create those inside your package.
