### ISSUE TITLE
lesson_score not set for SCORM 2004 with cmi.score.scaled

### ISSUE THREAD

**Issue by bryanlandia** [overhangio/openedx-scorm-xblock#55]
The `set_value` method only sets a `lesson_score` for `cmi.core.score.raw` or `cmi.score.raw`.  SCORM 2004 packages can report score with `cmi.score.scaled`.

**Comment by bryanlandia** [comment]
I'll work on a PR for this

**Comment by DawoudSheraz** [comment]
Hi, can you add some context as to why this change is needed and if it can impact any existing data? The current description does not give enough context. Thanks.

**Comment by ziafazal** [comment]
@bryanlandia v17.0.1 has fix for this one
