### ISSUE TITLE
Grades not set correctly in LMS if lesson_score not updated before completion or pass/fail

### ISSUE THREAD

**Issue by bryanlandia** [overhangio/openedx-scorm-xblock#56]
Some packages may send a `cmi.core.lesson_status`, `cmi.success_status`, or `cmi.completion_status` prior to ever recording a score or the final score.  In this case, `get_grade` could be evaluated with a 0 or otherwise not up-to-date score, and this will be sent to the LMS.   The `set_value` method should update the grade in the LMS even if already passed/failed/completed to avoid missing the updated score.

**Comment by bryanlandia** [comment]
I'll submit a PR for this

**Comment by ziafazal** [comment]
@bryanlandia v17.0.1 has fix for this one.
