### ISSUE TITLE
Does this xblock update any student grade 

### ISSUE THREAD

**Issue by mumarkhan999** [overhangio/openedx-scorm-xblock#6]
I have installed this xblock on juniper relaese of openedx. I have imported a scorm file inside a unit of a course. And I have marked that particular subsection as graded. But when I complete that scorm course, it doesn't update the grade of the student for that particular subsection. I have gone through the codebase and I know that there is no such code is written in the xblock, just the emitting of publish_grade event has been handled.

I wanna guidance, that how to mark grade for the student for that particular subsection which contains the scorm file.

**Comment by regisb** [comment]
This xblock *does* support grading. It might be that your scorm package does not properly send grading events to the xblock runtime -- it's difficult to know without trying out the scorm package myself. Unfortunately, Github issues are not for user support. Please ask your question on the [community forums](https://discuss.overhang.io).
