### ISSUE TITLE
Scorm xblock Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/openedx-scorm-xblock#67]
- [ ] Ensure scorm xblock is compatible with Python 3.12. Add appropriate CI checks and ensure that scorm works as expected in both Python 3.8 and 3.12.

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by DawoudSheraz** [comment]
@ahmed-arb Let's also add Python 3.12 CI checks and then close this one out.

**Comment by ahmed-arb** [comment]
Currently there are no CI checks for this repo.
