### ISSUE TITLE
[bug] Fullscreen blocks content if height is greater than screen height

### ISSUE THREAD

**Issue by KristinAoki** [overhangio/openedx-scorm-xblock#92]
> Full screen navigation is very hard to navigate and makes it impossible for users to scroll down completely and access the content. It completely hides the buttons making it impossible to move forward. They have to exit full screen to continue to navigate.
>
> Happens only on certain devices (like a laptop), does not happen as often at higher resolutions.

The solution would be to have the height of `<div class="scorm-pane " />` updated to the screen height if it is less than the saved height. The following changes will need to be made:

1. https://github.com/overhangio/openedx-scorm-xblock/blob/ea54a52295ea898d79bfaa63013354b908b5c886/openedxscorm/static/js/src/scormxblock.js#L54-L62
Update the function to include height changes
```
function onFullscreenChange(e) {
        if (isFullscreen()) {
            $(e.target).addClass("fullscreen-enabled");
            // NEW LINE
            if (settings.block_height > screen.height) {
                $(e.target).css("height", screen.height);
            }
        } else {
            $(e.target).removeClass("fullscreen-enabled");
            // NEW LINE
            $(e.target).css("height", settings.block_height);
        }
        // This is required to trigger the actual content resize in some packages
        window.dispatchEvent(new Event('resize'));
}
```

2. https://github.com/overhangio/openedx-scorm-xblock/blob/ea54a52295ea898d79bfaa63013354b908b5c886/openedxscorm/scormxblock.py#L237-L246
Add `block_height` to `json_args`
```
"block_height": self.height or 450,
```

**Comment by DawoudSheraz** [comment]
@Danyal-Faheem FYI
